# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/himanshu/Projects/slider-prism

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/himanshu/Projects/slider-prism

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/himanshu/Projects/slider-prism/CMakeFiles /home/himanshu/Projects/slider-prism//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/himanshu/Projects/slider-prism/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slider-prism

# Build rule for target.
slider-prism: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slider-prism
.PHONY : slider-prism

# fast build rule for target.
slider-prism/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/build
.PHONY : slider-prism/fast

src/core/game.o: src/core/game.c.o
.PHONY : src/core/game.o

# target to build an object file
src/core/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/game.c.o
.PHONY : src/core/game.c.o

src/core/game.i: src/core/game.c.i
.PHONY : src/core/game.i

# target to preprocess a source file
src/core/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/game.c.i
.PHONY : src/core/game.c.i

src/core/game.s: src/core/game.c.s
.PHONY : src/core/game.s

# target to generate assembly for a file
src/core/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/game.c.s
.PHONY : src/core/game.c.s

src/core/scenes/playscene.o: src/core/scenes/playscene.c.o
.PHONY : src/core/scenes/playscene.o

# target to build an object file
src/core/scenes/playscene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/playscene.c.o
.PHONY : src/core/scenes/playscene.c.o

src/core/scenes/playscene.i: src/core/scenes/playscene.c.i
.PHONY : src/core/scenes/playscene.i

# target to preprocess a source file
src/core/scenes/playscene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/playscene.c.i
.PHONY : src/core/scenes/playscene.c.i

src/core/scenes/playscene.s: src/core/scenes/playscene.c.s
.PHONY : src/core/scenes/playscene.s

# target to generate assembly for a file
src/core/scenes/playscene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/playscene.c.s
.PHONY : src/core/scenes/playscene.c.s

src/core/scenes/scenes.o: src/core/scenes/scenes.c.o
.PHONY : src/core/scenes/scenes.o

# target to build an object file
src/core/scenes/scenes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/scenes.c.o
.PHONY : src/core/scenes/scenes.c.o

src/core/scenes/scenes.i: src/core/scenes/scenes.c.i
.PHONY : src/core/scenes/scenes.i

# target to preprocess a source file
src/core/scenes/scenes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/scenes.c.i
.PHONY : src/core/scenes/scenes.c.i

src/core/scenes/scenes.s: src/core/scenes/scenes.c.s
.PHONY : src/core/scenes/scenes.s

# target to generate assembly for a file
src/core/scenes/scenes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/scenes.c.s
.PHONY : src/core/scenes/scenes.c.s

src/core/scenes/splashscene.o: src/core/scenes/splashscene.c.o
.PHONY : src/core/scenes/splashscene.o

# target to build an object file
src/core/scenes/splashscene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/splashscene.c.o
.PHONY : src/core/scenes/splashscene.c.o

src/core/scenes/splashscene.i: src/core/scenes/splashscene.c.i
.PHONY : src/core/scenes/splashscene.i

# target to preprocess a source file
src/core/scenes/splashscene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/splashscene.c.i
.PHONY : src/core/scenes/splashscene.c.i

src/core/scenes/splashscene.s: src/core/scenes/splashscene.c.s
.PHONY : src/core/scenes/splashscene.s

# target to generate assembly for a file
src/core/scenes/splashscene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/splashscene.c.s
.PHONY : src/core/scenes/splashscene.c.s

src/core/scenes/titlescene.o: src/core/scenes/titlescene.c.o
.PHONY : src/core/scenes/titlescene.o

# target to build an object file
src/core/scenes/titlescene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/titlescene.c.o
.PHONY : src/core/scenes/titlescene.c.o

src/core/scenes/titlescene.i: src/core/scenes/titlescene.c.i
.PHONY : src/core/scenes/titlescene.i

# target to preprocess a source file
src/core/scenes/titlescene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/titlescene.c.i
.PHONY : src/core/scenes/titlescene.c.i

src/core/scenes/titlescene.s: src/core/scenes/titlescene.c.s
.PHONY : src/core/scenes/titlescene.s

# target to generate assembly for a file
src/core/scenes/titlescene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/core/scenes/titlescene.c.s
.PHONY : src/core/scenes/titlescene.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/main.c.s
.PHONY : src/main.c.s

src/prismatic/logger/logger.o: src/prismatic/logger/logger.c.o
.PHONY : src/prismatic/logger/logger.o

# target to build an object file
src/prismatic/logger/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/logger/logger.c.o
.PHONY : src/prismatic/logger/logger.c.o

src/prismatic/logger/logger.i: src/prismatic/logger/logger.c.i
.PHONY : src/prismatic/logger/logger.i

# target to preprocess a source file
src/prismatic/logger/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/logger/logger.c.i
.PHONY : src/prismatic/logger/logger.c.i

src/prismatic/logger/logger.s: src/prismatic/logger/logger.c.s
.PHONY : src/prismatic/logger/logger.s

# target to generate assembly for a file
src/prismatic/logger/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/logger/logger.c.s
.PHONY : src/prismatic/logger/logger.c.s

src/prismatic/prismatic.o: src/prismatic/prismatic.c.o
.PHONY : src/prismatic/prismatic.o

# target to build an object file
src/prismatic/prismatic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/prismatic.c.o
.PHONY : src/prismatic/prismatic.c.o

src/prismatic/prismatic.i: src/prismatic/prismatic.c.i
.PHONY : src/prismatic/prismatic.i

# target to preprocess a source file
src/prismatic/prismatic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/prismatic.c.i
.PHONY : src/prismatic/prismatic.c.i

src/prismatic/prismatic.s: src/prismatic/prismatic.c.s
.PHONY : src/prismatic/prismatic.s

# target to generate assembly for a file
src/prismatic/prismatic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/prismatic.c.s
.PHONY : src/prismatic/prismatic.c.s

src/prismatic/scene/scene.o: src/prismatic/scene/scene.c.o
.PHONY : src/prismatic/scene/scene.o

# target to build an object file
src/prismatic/scene/scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/scene/scene.c.o
.PHONY : src/prismatic/scene/scene.c.o

src/prismatic/scene/scene.i: src/prismatic/scene/scene.c.i
.PHONY : src/prismatic/scene/scene.i

# target to preprocess a source file
src/prismatic/scene/scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/scene/scene.c.i
.PHONY : src/prismatic/scene/scene.c.i

src/prismatic/scene/scene.s: src/prismatic/scene/scene.c.s
.PHONY : src/prismatic/scene/scene.s

# target to generate assembly for a file
src/prismatic/scene/scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/scene/scene.c.s
.PHONY : src/prismatic/scene/scene.c.s

src/prismatic/sprite/sprite.o: src/prismatic/sprite/sprite.c.o
.PHONY : src/prismatic/sprite/sprite.o

# target to build an object file
src/prismatic/sprite/sprite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/sprite/sprite.c.o
.PHONY : src/prismatic/sprite/sprite.c.o

src/prismatic/sprite/sprite.i: src/prismatic/sprite/sprite.c.i
.PHONY : src/prismatic/sprite/sprite.i

# target to preprocess a source file
src/prismatic/sprite/sprite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/sprite/sprite.c.i
.PHONY : src/prismatic/sprite/sprite.c.i

src/prismatic/sprite/sprite.s: src/prismatic/sprite/sprite.c.s
.PHONY : src/prismatic/sprite/sprite.s

# target to generate assembly for a file
src/prismatic/sprite/sprite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/sprite/sprite.c.s
.PHONY : src/prismatic/sprite/sprite.c.s

src/prismatic/state/state_machine.o: src/prismatic/state/state_machine.c.o
.PHONY : src/prismatic/state/state_machine.o

# target to build an object file
src/prismatic/state/state_machine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/state/state_machine.c.o
.PHONY : src/prismatic/state/state_machine.c.o

src/prismatic/state/state_machine.i: src/prismatic/state/state_machine.c.i
.PHONY : src/prismatic/state/state_machine.i

# target to preprocess a source file
src/prismatic/state/state_machine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/state/state_machine.c.i
.PHONY : src/prismatic/state/state_machine.c.i

src/prismatic/state/state_machine.s: src/prismatic/state/state_machine.c.s
.PHONY : src/prismatic/state/state_machine.s

# target to generate assembly for a file
src/prismatic/state/state_machine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/state/state_machine.c.s
.PHONY : src/prismatic/state/state_machine.c.s

src/prismatic/text/text.o: src/prismatic/text/text.c.o
.PHONY : src/prismatic/text/text.o

# target to build an object file
src/prismatic/text/text.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/text/text.c.o
.PHONY : src/prismatic/text/text.c.o

src/prismatic/text/text.i: src/prismatic/text/text.c.i
.PHONY : src/prismatic/text/text.i

# target to preprocess a source file
src/prismatic/text/text.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/text/text.c.i
.PHONY : src/prismatic/text/text.c.i

src/prismatic/text/text.s: src/prismatic/text/text.c.s
.PHONY : src/prismatic/text/text.s

# target to generate assembly for a file
src/prismatic/text/text.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/text/text.c.s
.PHONY : src/prismatic/text/text.c.s

src/prismatic/tilemap/ldtk.o: src/prismatic/tilemap/ldtk.c.o
.PHONY : src/prismatic/tilemap/ldtk.o

# target to build an object file
src/prismatic/tilemap/ldtk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/tilemap/ldtk.c.o
.PHONY : src/prismatic/tilemap/ldtk.c.o

src/prismatic/tilemap/ldtk.i: src/prismatic/tilemap/ldtk.c.i
.PHONY : src/prismatic/tilemap/ldtk.i

# target to preprocess a source file
src/prismatic/tilemap/ldtk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/tilemap/ldtk.c.i
.PHONY : src/prismatic/tilemap/ldtk.c.i

src/prismatic/tilemap/ldtk.s: src/prismatic/tilemap/ldtk.c.s
.PHONY : src/prismatic/tilemap/ldtk.s

# target to generate assembly for a file
src/prismatic/tilemap/ldtk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/tilemap/ldtk.c.s
.PHONY : src/prismatic/tilemap/ldtk.c.s

src/prismatic/transition/transition.o: src/prismatic/transition/transition.c.o
.PHONY : src/prismatic/transition/transition.o

# target to build an object file
src/prismatic/transition/transition.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/transition/transition.c.o
.PHONY : src/prismatic/transition/transition.c.o

src/prismatic/transition/transition.i: src/prismatic/transition/transition.c.i
.PHONY : src/prismatic/transition/transition.i

# target to preprocess a source file
src/prismatic/transition/transition.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/transition/transition.c.i
.PHONY : src/prismatic/transition/transition.c.i

src/prismatic/transition/transition.s: src/prismatic/transition/transition.c.s
.PHONY : src/prismatic/transition/transition.s

# target to generate assembly for a file
src/prismatic/transition/transition.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/transition/transition.c.s
.PHONY : src/prismatic/transition/transition.c.s

src/prismatic/utils/utils.o: src/prismatic/utils/utils.c.o
.PHONY : src/prismatic/utils/utils.o

# target to build an object file
src/prismatic/utils/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/utils/utils.c.o
.PHONY : src/prismatic/utils/utils.c.o

src/prismatic/utils/utils.i: src/prismatic/utils/utils.c.i
.PHONY : src/prismatic/utils/utils.i

# target to preprocess a source file
src/prismatic/utils/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/utils/utils.c.i
.PHONY : src/prismatic/utils/utils.c.i

src/prismatic/utils/utils.s: src/prismatic/utils/utils.c.s
.PHONY : src/prismatic/utils/utils.s

# target to generate assembly for a file
src/prismatic/utils/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slider-prism.dir/build.make CMakeFiles/slider-prism.dir/src/prismatic/utils/utils.c.s
.PHONY : src/prismatic/utils/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... slider-prism"
	@echo "... src/core/game.o"
	@echo "... src/core/game.i"
	@echo "... src/core/game.s"
	@echo "... src/core/scenes/playscene.o"
	@echo "... src/core/scenes/playscene.i"
	@echo "... src/core/scenes/playscene.s"
	@echo "... src/core/scenes/scenes.o"
	@echo "... src/core/scenes/scenes.i"
	@echo "... src/core/scenes/scenes.s"
	@echo "... src/core/scenes/splashscene.o"
	@echo "... src/core/scenes/splashscene.i"
	@echo "... src/core/scenes/splashscene.s"
	@echo "... src/core/scenes/titlescene.o"
	@echo "... src/core/scenes/titlescene.i"
	@echo "... src/core/scenes/titlescene.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/prismatic/logger/logger.o"
	@echo "... src/prismatic/logger/logger.i"
	@echo "... src/prismatic/logger/logger.s"
	@echo "... src/prismatic/prismatic.o"
	@echo "... src/prismatic/prismatic.i"
	@echo "... src/prismatic/prismatic.s"
	@echo "... src/prismatic/scene/scene.o"
	@echo "... src/prismatic/scene/scene.i"
	@echo "... src/prismatic/scene/scene.s"
	@echo "... src/prismatic/sprite/sprite.o"
	@echo "... src/prismatic/sprite/sprite.i"
	@echo "... src/prismatic/sprite/sprite.s"
	@echo "... src/prismatic/state/state_machine.o"
	@echo "... src/prismatic/state/state_machine.i"
	@echo "... src/prismatic/state/state_machine.s"
	@echo "... src/prismatic/text/text.o"
	@echo "... src/prismatic/text/text.i"
	@echo "... src/prismatic/text/text.s"
	@echo "... src/prismatic/tilemap/ldtk.o"
	@echo "... src/prismatic/tilemap/ldtk.i"
	@echo "... src/prismatic/tilemap/ldtk.s"
	@echo "... src/prismatic/transition/transition.o"
	@echo "... src/prismatic/transition/transition.i"
	@echo "... src/prismatic/transition/transition.s"
	@echo "... src/prismatic/utils/utils.o"
	@echo "... src/prismatic/utils/utils.i"
	@echo "... src/prismatic/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

